-- Sheltr: evacuation_centers (PostGIS) — safe to re-run on Supabase (idempotent pieces).
-- If you already created the table in the dashboard, this mainly adds summary, trigger, RLS, and RPC.

create extension if not exists postgis;

-- Base table (matches Supabase table editor; adds optional summary for in-app copy)
create table if not exists public.evacuation_centers (
  id bigint generated by default as identity not null,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  is_open boolean null default true,
  location geography (point, 4326) null,
  capacity integer null,
  safety_score double precision null,
  type text null,
  constraint evacuation_centers_pkey primary key (id)
);

alter table public.evacuation_centers
  add column if not exists summary text;

create index if not exists evacuation_centers_geo_index
  on public.evacuation_centers using gist (location);

-- Keep geography in sync with latitude/longitude (for inserts from SQL editor or API)
create or replace function public.evacuation_centers_set_location()
returns trigger
language plpgsql
as $$
begin
  if new.longitude is not null and new.latitude is not null then
    new.location := st_setsrid(st_makepoint(new.longitude, new.latitude), 4326)::geography;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_evacuation_centers_set_location on public.evacuation_centers;
create trigger trg_evacuation_centers_set_location
  before insert or update of latitude, longitude on public.evacuation_centers
  for each row
  execute function public.evacuation_centers_set_location();

-- Backfill location for rows created before the trigger
update public.evacuation_centers e
set location = st_setsrid(st_makepoint(e.longitude, e.latitude), 4326)::geography
where e.location is null;

-- Nearest centers (PostGIS KNN). Uses public schema explicitly.
create or replace function public.get_nearest_evacuation(user_lat double precision, user_lon double precision)
returns table (
  id bigint,
  name text,
  lat double precision,
  lon double precision,
  dist_meters double precision
)
language sql
stable
as $$
  select
    e.id,
    e.name,
    e.latitude as lat,
    e.longitude as lon,
    st_distance(
      e.location,
      st_setsrid(st_makepoint(user_lon, user_lat), 4326)::geography
    )::double precision as dist_meters
  from public.evacuation_centers e
  where coalesce(e.is_open, true) = true
    and e.location is not null
  order by e.location <-> st_setsrid(st_makepoint(user_lon, user_lat), 4326)::geography
  limit 5;
$$;

alter table public.evacuation_centers enable row level security;

drop policy if exists "Allow public read evacuation_centers" on public.evacuation_centers;
create policy "Allow public read evacuation_centers"
  on public.evacuation_centers
  for select
  to anon, authenticated
  using (true);

grant select on table public.evacuation_centers to anon, authenticated;

grant execute on function public.get_nearest_evacuation(double precision, double precision) to anon, authenticated;
